# Generated by Django 2.2.10 on 2020-04-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200403_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='username',
        ),
    ]
