# Generated by Django 2.2.10 on 2020-04-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200404_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='username',
        ),
    ]
