# Generated by Django 2.2.10 on 2020-07-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_defaultrecommendation_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
